"""Deterministic layout engine: semantic InstructionSpec -> renderer contract.

The model decides *what* the parts and steps are; this module decides *where*
each part is drawn. That keeps precise 2D geometry out of the model (which
small VLMs handle poorly) while still producing a clean, exploded, IKEA-style
manual that the existing browser renderer (public/app.js) can draw.

Output matches the `instruction_model` shape the renderer expects:
  { version, renderer, source, view_box, parts:[...], frames:[...] }
Each part carries a `color` so pieces read as separated and color-coded.
"""

from __future__ import annotations

from typing import Dict, List, Optional

from .schemas import InstructionSpec

VIEW_BOX = {"width": 520, "height": 360}
EXPLODE_DY = 48  # how far a newly added part floats above its assembled slot

# --- Assembled slot tables (canvas 520x360) --------------------------------
TABLE_SLOTS = {
    "top_single": {"x": 130, "y": 70, "width": 260, "height": 48},
    "top_half_left": {"x": 98, "y": 74, "width": 162, "height": 150, "depth": 14},
    "top_half_right": {"x": 260, "y": 74, "width": 162, "height": 150, "depth": 14},
    "connector": {"x": 236, "y": 120, "width": 48, "height": 18},
    "apron": [
        {"x": 150, "y": 150, "width": 220, "height": 16},
        {"x": 150, "y": 222, "width": 220, "height": 16},
        {"x": 150, "y": 160, "width": 16, "height": 78},
        {"x": 354, "y": 160, "width": 16, "height": 78},
    ],
    "leg": [
        {"x": 140, "y": 150, "width": 30, "height": 130, "tilt": -7},
        {"x": 350, "y": 150, "width": 30, "height": 130, "tilt": 7},
        {"x": 176, "y": 150, "width": 26, "height": 130, "tilt": 6},
        {"x": 318, "y": 150, "width": 26, "height": 130, "tilt": -6},
    ],
    "brace": [
        {"x": 176, "y": 250, "width": 168, "height": 14, "angle": -18},
        {"x": 176, "y": 250, "width": 168, "height": 14, "angle": 18},
    ],
    "foot": [
        {"x": 150, "y": 300, "width": 220, "height": 14},
        {"x": 150, "y": 314, "width": 220, "height": 12},
    ],
}

SHELF_SLOTS = {
    "side": [
        {"x": 150, "y": 78, "width": 24, "height": 212},
        {"x": 346, "y": 78, "width": 24, "height": 212},
    ],
    "back": {"x": 174, "y": 80, "width": 172, "height": 208},
}

# Roles drawn in the scene vs. surfaced as hardware count insets.
_INSET_ROLES = {"fastener", "leveler"}


def build_instruction_model(spec: InstructionSpec) -> dict:
    parts_by_id = {p.id: p for p in spec.parts}
    topology = spec.topology if spec.topology in {"table", "shelf"} else "table"

    assembled = _assign_slots(spec, topology)
    render_parts = _render_parts(spec, assembled)

    frames: List[dict] = []
    introduced: List[str] = []
    for index, step in enumerate(spec.steps):
        new_ids = [pid for pid in step.add_parts if pid in parts_by_id]
        introduced.extend(pid for pid in new_ids if pid not in introduced)
        visible = [pid for pid in introduced if pid in assembled]
        highlight = [pid for pid in new_ids if pid in assembled]

        placements: Dict[str, dict] = {}
        arrows: List[dict] = []
        for pid in visible:
            base = assembled[pid]
            if pid in highlight:
                exploded, arrow = _explode(base, parts_by_id[pid])
                placements[pid] = exploded
                if arrow:
                    arrows.append(arrow)
            else:
                placements[pid] = base

        insets = _hardware_insets(step, highlight, assembled)
        callouts = []
        if index == 0:
            callouts.append({"text": spec.object_type, "x": 260, "y": 60})

        frames.append(
            {
                "title": step.title or f"Step {index + 1}",
                "caption": step.action or step.note or "",
                "parts_needed": [
                    {"part_id": pid, "quantity": parts_by_id[pid].quantity}
                    for pid in new_ids
                ]
                + [
                    {"part_id": pid, "quantity": parts_by_id[pid].quantity}
                    for pid in step.add_parts
                    if pid in _INSET_ROLE_IDS(spec)
                ],
                "visible_parts": visible,
                "highlight_parts": highlight,
                "placements": placements,
                "arrows": arrows,
                "insets": insets,
                "callouts": callouts,
            }
        )

    return {
        "version": "1.0",
        "renderer": "model_instruction_layout",
        "source": "vlm_instruction_spec",
        "source_note": (
            "Parts and assembly order generated by the local vision-language "
            "model; positions and the exploded color-coded drawing produced by "
            "a deterministic layout engine."
        ),
        "view_box": dict(VIEW_BOX),
        "parts": render_parts,
        "frames": frames,
    }


# ---------------------------------------------------------------------------
def _assign_slots(spec: InstructionSpec, topology: str) -> Dict[str, dict]:
    """Map each scene part id to its assembled geometry."""
    assembled: Dict[str, dict] = {}
    slots = TABLE_SLOTS if topology == "table" else SHELF_SLOTS

    by_role: Dict[str, List] = {}
    for part in spec.parts:
        by_role.setdefault(part.role, []).append(part)

    if topology == "table":
        _assign_table(by_role, slots, assembled)
    else:
        _assign_shelf(by_role, slots, assembled)

    # Generic / unrecognized parts: stack them as rails down the right margin.
    leftovers = [
        p
        for p in spec.parts
        if p.id not in assembled and p.role not in _INSET_ROLES
    ]
    for i, part in enumerate(leftovers):
        assembled[part.id] = {"x": 150, "y": 120 + i * 26, "width": 200, "height": 16}

    return assembled


def _assign_table(by_role, slots, assembled) -> None:
    halves_l = by_role.get("top_half_left", [])
    halves_r = by_role.get("top_half_right", [])
    if halves_l or halves_r:
        if halves_l:
            assembled[halves_l[0].id] = dict(slots["top_half_left"])
        if halves_r:
            assembled[halves_r[0].id] = dict(slots["top_half_right"])
    else:
        for p in by_role.get("top", [])[:1]:
            assembled[p.id] = dict(slots["top_single"])

    for p in by_role.get("connector", [])[:1]:
        assembled[p.id] = dict(slots["connector"])
    _assign_list(by_role.get("apron", []), slots["apron"], assembled)
    _assign_list(by_role.get("leg", []), slots["leg"], assembled)
    _assign_list(by_role.get("brace", []), slots["brace"], assembled)
    _assign_list(by_role.get("foot", []), slots["foot"], assembled)


def _assign_shelf(by_role, slots, assembled) -> None:
    _assign_list(by_role.get("side", []), slots["side"], assembled)
    for p in by_role.get("back", [])[:1]:
        assembled[p.id] = dict(slots["back"])
    shelves = by_role.get("shelf", [])
    n = max(len(shelves), 1)
    top, bottom = 92, 286
    for i, p in enumerate(shelves):
        y = top + round((bottom - top) * (i / max(n - 1, 1))) if n > 1 else 150
        assembled[p.id] = {"x": 174, "y": y, "width": 172, "height": 14}
    _assign_list(by_role.get("foot", []), slots.get("foot", []), assembled)


def _assign_list(parts, slot_list, assembled) -> None:
    for i, part in enumerate(parts):
        if i < len(slot_list):
            assembled[part.id] = dict(slot_list[i])


def _render_parts(spec: InstructionSpec, assembled: Dict[str, dict]) -> List[dict]:
    out = []
    for part in spec.parts:
        out.append(
            {
                "id": part.id,
                "label": part.label,
                "role": part.role,
                "kind": _kind_for(part),
                "material_name": part.material_name,
                "cut_size": part.cut_size,
                "quantity": part.quantity,
                "color": part.color,
                "geometry": assembled.get(part.id, {}),
            }
        )
    return out


def _kind_for(part) -> str:
    role, shape = part.role, part.shape
    if role == "top_half_left":
        return "round_top_half_left" if shape == "round_half" else "panel"
    if role == "top_half_right":
        return "round_top_half_right" if shape == "round_half" else "panel"
    if role in {"top", "shelf", "side", "back"}:
        return "panel"
    if role == "leg":
        return "angled_leg"
    if role == "brace":
        return "cross_beam"
    if role in {"apron", "foot"}:
        return "rail"
    if role == "connector":
        return "metal_connector"
    if role == "fastener":
        return "fastener_set"
    if role == "leveler":
        return "leveler_set"
    return "rail"


def _explode(base: dict, part) -> (dict, Optional[dict]):
    """Return an exploded placement for a newly added part plus an arrow."""
    g = dict(base)
    if "points" in g or "lines" in g:
        return g, None
    # Round halves slide in horizontally toward the seam.
    if part.role == "top_half_left":
        g["x"] = base["x"] - 30
        return g, {"from": [base["x"] + base.get("width", 0) - 30, base["y"] + 60],
                   "to": [base["x"] + base.get("width", 0) - 4, base["y"] + 60]}
    if part.role == "top_half_right":
        g["x"] = base["x"] + 30
        return g, {"from": [base["x"] + 30, base["y"] + 60], "to": [base["x"] + 4, base["y"] + 60]}
    # Everything else drops down into place.
    if "x" in g and "y" in g:
        cx = g["x"] + g.get("width", 40) / 2
        g["y"] = base["y"] - EXPLODE_DY
        return g, {"from": [cx, g["y"] + g.get("height", 16) + 6], "to": [cx, base["y"] - 4]}
    return g, None


def _hardware_insets(step, highlight, assembled) -> List[dict]:
    insets = []
    spots = [
        {"x": 432, "y": 100, "r": 40},
        {"x": 432, "y": 238, "r": 40},
    ]
    target = None
    if highlight:
        g = assembled.get(highlight[0], {})
        if "x" in g:
            target = [g["x"] + g.get("width", 30) / 2, g["y"]]
    for i, hw in enumerate(step.hardware[:2]):
        spot = spots[i]
        insets.append(
            {
                "type": _hardware_type(hw.name),
                "label": f"{hw.count}x",
                "x": spot["x"],
                "y": spot["y"],
                "r": spot["r"],
                **({"to": target} if target else {}),
            }
        )
    return insets


def _hardware_type(name: str) -> str:
    low = (name or "").lower()
    if "connector" in low or "cam" in low or "dowel" in low:
        return "connector"
    if "level" in low or "foot" in low or "glide" in low:
        return "leveler"
    return "screw"


def _INSET_ROLE_IDS(spec: InstructionSpec) -> set:
    return {p.id for p in spec.parts if p.role in _INSET_ROLES}
